// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkgglasdvehqqcyzpbgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprZ2dsYXNkdmVocXFjeXpwYmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzEzMjEsImV4cCI6MjA3MDAwNzMyMX0.ZMpPAWaG4CAna9m5rCn3riWk1a3LFYRJAJ9NeOEFNOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'pkce',
  }
});